apiVersion: batch/v1
kind: Job
metadata:
  name: force-sync-example
  annotations:
    # Try commenting me out and making a chance after.
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "6"]
      restartPolicy: Never