apiVersion: batch/v1
kind: Job
metadata:
  name: force-sync-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never