apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: force-sync-annotation
spec:
  destination:
    namespace: force-sync-annotation
    name: in-cluster
  project: default
  source:
    path: features/5-force-sync-annotation
    repoURL: https://github.com/morey-tech/argocd-v2.12-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true